{{- if .Values.secrets.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hasura-chart.fullname" . }}
type: Opaque
data:
  accessKey: {{ .Values.secrets.accessKey | b64enc | quote }}
  # only change postgres username, password and dbname as set
  # in postgres secret
  # --set secrets.dburl=postgres://hasurauser:MyPassWd123@postgres:5432/hasura
  dburl: {{ .Values.secrets.dburl | b64enc | quote }}
{{- end }}
