# https://kubernetes.github.io/ingress-nginx/user-guide/basic-usage/
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hasura
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

spec:
  tls:
  - hosts:
    - kubernetes.docker.internal
  rules:
  - host: kubernetes.docker.internal
    http:
      paths:
      - path: /
        backend:
          serviceName: hasura
          servicePort: 8080
