kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/k8s-hasura-test"